mod cli;
mod daemon;
mod error;
mod exec;
mod grant;
mod install;
mod job;
mod local;
mod mesh;
mod notify;
mod pair;
mod paths;
mod pin;
mod request;
mod store;
mod tailscale;
mod tray;
mod types;

pub use cli::{parse_argv, Cmd};
pub use daemon::{dispatch, serve, serve_local};
pub use error::ClixError;
pub use exec::run_granted;
pub use grant::{add, check, check_at, consume_once, hands, remove, resolve_tool};
pub use local::client_send;
pub use mesh::{call as mesh_call, MeshHandle, MeshListener};
pub use notify::{notify_request, set_notify_hook, NotifyHook};
pub use pair::{pair_join, pair_listen, phrase};
pub use paths::{socket_path, state_dir, state_file};
pub use pin::{sync as pin_sync, sync_after_pair};
pub use store::Store;
pub use tailscale::{tailscale_status, PeerAddr};
pub use tray::tray_tooltip;
pub use types::{BodyId, Grant, Job, JobStatus, OwnerId, Peer, Request, Schedule};
